# Generated by Django 4.1.3 on 2023-04-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_group'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleblock',
            name='groups',
            field=models.ManyToManyField(related_name='schedule_blocks', to='users.group'),
        ),
    ]
