# Generated by Django 4.1.3 on 2023-10-11 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_scheduleblock_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='month',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='schedule',
            name='worksheet_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name='scheduleblock',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_blocks', to='schedule.schedule'),
        ),
        migrations.AddField(
            model_name='scheduleblock',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
