# Generated by Django 4.1.3 on 2023-10-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturers', '0001_initial'),
        ('users', '0002_group'),
        ('rooms', '0001_initial'),
        ('courses', '0002_alter_course_groups_alter_groupcoursethrough_group_and_more'),
        ('schedule', '0004_schedule_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleblock',
            name='schedule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='schedules', to='courses.course'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='errors',
            field=models.JSONField(default=list, blank=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='schedules', to='users.group'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='lecturers',
            field=models.ManyToManyField(blank=True, related_name='schedules', to='lecturers.lecturer'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='schedules', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_blocks',
            field=models.ManyToManyField(blank=True, related_name='schedules', to='schedule.scheduleblock'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='progress',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
