# Generated by Django 4.1.3 on 2023-10-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_remove_scheduleblock_schedule_schedule_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='replaced_schedule_blocks',
            field=models.ManyToManyField(blank=True, related_name='schedules_replaced', to='schedule.scheduleblock'),
        ),
    ]
