# Generated by Django 4.1.3 on 2023-11-20 20:39

from django.db import migrations, models
import schedule.utils


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_schedule_replaced_schedule_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleblock',
            name='colour',
            field=models.CharField(blank=True, max_length=9, help_text="format: #00000000 (ARGB)"),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='month',
            field=models.IntegerField(default=schedule.utils.get_current_month),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='year',
            field=models.IntegerField(default=schedule.utils.get_current_year),
        ),
    ]
