# Generated by Django 4.1.3 on 2022-11-13 21:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Lecturer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=128)),
                ("last_name", models.CharField(max_length=128)),
                ("title", models.CharField(max_length=128, blank=True)),
                ("job_position", models.CharField(max_length=128, blank=True)),
                ("contact_email", models.CharField(max_length=128, blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
